default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

development:
  <<: *default
  database: mckrulvey_haus_development

test:
  <<: *default
  database: mckrulvey_haus_test

production:
  primary: &primary_production
    <<: *default
    database: mckrulvey_haus_production
  cache:
    <<: *primary_production
    database: mckrulvey_haus_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mckrulvey_haus_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mckrulvey_haus_production_cable
    migrations_paths: db/cable_migrate
