production:
  schedule_notifications:
    class: ScheduleNotificationsJob
    schedule: every 5 minutes

development:
  schedule_notifications:
    class: ScheduleNotificationsJob
    schedule: every 5 minutes

